In [1]:
import pandas as pd
import duckdb

In [2]:
con = duckdb.connect("../../dev.duckdb")

In [3]:
df_pop = con.sql("SELECT * FROM population_code_geo").df()
df_pop_final = con.sql("SELECT * FROM population_par_com_annee").df()

In [5]:
df_pop[df_pop["code_geo"].str.startswith('976')]

,code_geo,nom_geo,code_departement,pop_2016,pop_2017,pop_2018,pop_2019,pop_2020,pop_2021,pop_2022,pop_2023,pop_2024,pop_2025,pop_2026,code_region
34995,97601,Acoua,976,NaN,NaN,NaN,NaN,5384,NaN,NaN,NaN,NaN,NaN,NaN,6
34996,97602,Bandraboua,976,NaN,NaN,NaN,NaN,14211,NaN,NaN,NaN,NaN,NaN,NaN,6
34997,97603,Bandrele,976,NaN,NaN,NaN,NaN,10529,NaN,NaN,NaN,NaN,NaN,NaN,6
34998,97604,Bouéni,976,NaN,NaN,NaN,NaN,6503,NaN,NaN,NaN,NaN,NaN,NaN,6
34999,97605,Chiconi,976,NaN,NaN,NaN,NaN,8616,NaN,NaN,NaN,NaN,NaN,NaN,6
35000,97606,Chirongui,976,NaN,NaN,NaN,NaN,9197,NaN,NaN,NaN,NaN,NaN,NaN,6
35001,97607,Dembeni,976,NaN,NaN,NaN,NaN,16116,NaN,NaN,NaN,NaN,NaN,NaN,6
35002,97608,Dzaoudzi,976,NaN,NaN,NaN,NaN,18237,NaN,NaN,NaN,NaN,NaN,NaN,6
35003,97609,Kani-Kéli,976,NaN,NaN,NaN,NaN,5716,NaN,NaN,NaN,NaN,NaN,NaN,6
35004,97610,Koungou,976,NaN,NaN,NaN,NaN,32752,NaN,NaN,NaN,NaN,NaN,NaN,6
35005,97611,Mamoudzou,976,NaN,NaN,NaN,NaN,72974,NaN,NaN,NaN,NaN,NaN,NaN,6
35006,97612,Mtsamboro,976,NaN,NaN,NaN,NaN,8025,NaN,NaN,NaN,NaN,NaN,NaN,6
35007,97613,M’Tsangamouji,976,NaN,NaN,NaN,NaN,6586,NaN,NaN,NaN,NaN,NaN,NaN,6
35008,97614,Ouangani,976,NaN,NaN,NaN,NaN,10393,NaN,NaN,NaN,NaN,NaN,NaN,6
35009,97615,Pamandzi,976,NaN,NaN,NaN,NaN,11802,NaN,NaN,NaN,NaN,NaN,NaN,6
35010,97616,Sada,976,NaN,NaN,NaN,NaN,11619,NaN,NaN,NaN,NaN,NaN,NaN,6
35011,97617,Tsingoni,976,NaN,NaN,NaN,NaN,14235,NaN,NaN,NaN,NaN,NaN,NaN,6

In [4]:
df_pop_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 384759 entries, 0 to 384758
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   code_geo           384759 non-null  str
 1   annee_recensement  384759 non-null  int32
 2   annee              384759 non-null  int32
 3   population         384759 non-null  str
dtypes: int32(2), str(2)
memory usage: 11.8 MB

In [5]:
df_pop_final[df_pop_final["code_geo"].str.startswith('976')]

       code_geo  annee_recensement  annee population
174971    97601               2017   2020       5384
174972    97602               2017   2020      14211
174973    97603               2017   2020      10529
174974    97604               2017   2020       6503
174975    97605               2017   2020       8616
174976    97606               2017   2020       9197
174977    97607               2017   2020      16116
174978    97608               2017   2020      18237
174979    97609               2017   2020       5716
174980    97610               2017   2020      32752
174981    97611               2017   2020      72974
174982    97612               2017   2020       8025
174983    97613               2017   2020       6586
174984    97614               2017   2020      10393
174985    97615               2017   2020      11802
174986    97616               2017   2020      11619
174987    97617               2017   2020      14235