In [1]:
import pandas as pd
import duckdb

In [2]:
con = duckdb.connect('../../dev.duckdb')

In [7]:
df_score_tri = con.sql("SELECT * from indicateurs_tri_bats_par_com").df()

In [13]:
df_score_tri[df_score_tri["indicateur_tri"] > 0.7]

      code_geo  indicateur_tri
314      01370        0.759801
4361     13078        0.945308
4379     13096        0.994022
4485     14117        0.731773
8285     24501        0.802339
9687     27471        0.959788
9690     27474        0.769121
10954    30084        0.871261
12683    33434        0.861262
12732    33485        0.848834
13122    34324        0.869165
17079    47074        0.987940
17113    47108        0.869834
17124    47120        0.996172
17295    47298        0.974588
17301    47304        0.971053
17605    49288        0.962264
25992    66180        0.823571
25994    66182        0.967934
26023    66212        0.872750
32415    84063        0.977284

In [6]:
df_score_tri.info()

<class 'pandas.DataFrame'>
RangeIndex: 34875 entries, 0 to 34874
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   code_geo        34875 non-null  str
 1   indicateur_tri  34875 non-null  float64
dtypes: float64(1), str(1)
memory usage: 715.3 KB

In [5]:
df_score_tri["indicateur_tri"].describe()

count    34875.000000
mean         0.007306
std          0.047303
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          0.996172
Name: indicateur_tri, dtype: float64

In [3]:
df_score_rga = con.sql("SELECT * from indicateurs_rga_bats_par_com").df()
df_score_rga.head(5)

  code_geo  indicateur_rga
0    01001        0.060475
1    01002        0.095238
2    01004        0.183190
3    01005        0.065584
4    01006        0.025000

In [4]:
df_score_rga["indicateur_rga"].describe()

count    34782.000000
mean         0.173703
std          0.160225
min          0.000000
25%          0.047991
50%          0.126518
75%          0.261905
max          0.951724
Name: indicateur_rga, dtype: float64

In [5]:
df_score_rga[df_score_rga["indicateur_rga"] > 0.7]

      code_geo  indicateur_rga
1505     04001        0.797170
1525     04027        0.759804
1542     04047        0.704545
1592     04112        0.710601
1620     04145        0.743124
...        ...             ...
34468    91666        0.771624
34471    91679        0.844030
34476    91692        0.900000
34575    94048        0.940138
34588    94070        0.705365

[324 rows x 2 columns]