In [1]:
import pandas as pd
import duckdb

In [2]:
con = duckdb.connect('../../dev.duckdb')

In [3]:
df_ccr = con.sql("SELECT * from ccr_details").df()
df_catnat_histo = con.sql("SELECT * from catnat_historique").df()

In [4]:
df_ccr.info()

<class 'pandas.DataFrame'>
RangeIndex: 243032 entries, 0 to 243031
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   code_geo              243032 non-null  str
 1   nom_commune           243032 non-null  str
 2   date_debut_evenement  243032 non-null  datetime64[us]
 3   date_fin_evenement    243032 non-null  datetime64[us]
 4   date_arrete           243032 non-null  datetime64[us]
 5   date_parution_jo      243032 non-null  datetime64[us]
 6   nom_peril             243032 non-null  str
 7   franchise             243032 non-null  str
 8   libelle_avis          243032 non-null  str
 9   code_arrete           243032 non-null  int64
dtypes: datetime64[us](4), int64(1), str(5)
memory usage: 31.7 MB

In [ ]:
df_ccr[df_ccr["date_debut_evenement"] == df_ccr["date_fin_evenement"]]

,code_geo,nom_commune,date_debut_evenement,date_fin_evenement,date_arrete,date_parution_jo,nom_peril,franchise,libelle_avis,code_arrete
0,07005,ALBA LA ROMAINE,2025-11-16,2025-11-16,2026-01-19,2026-01-24,Inondations et/ou Coulées de Boue,-,Non reconnue,904
2,07181,LE POUZIN,2025-11-16,2025-11-16,2026-01-19,2026-01-24,Inondations et/ou Coulées de Boue,-,Non reconnue,904
4,07219,SAINT BAUZILE,2025-11-16,2025-11-16,2026-01-19,2026-01-24,Inondations et/ou Coulées de Boue,Simple,Reconnue,904
7,07270,SAINT MARTIN SUR LAVEZON,2025-11-16,2025-11-16,2026-01-19,2026-01-24,Inondations et/ou Coulées de Boue,Simple,Reconnue,904
8,07298,SAINT SYMPHORIEN SOUS CHOMERAC,2025-11-16,2025-11-16,2026-01-19,2026-01-24,Inondations et/ou Coulées de Boue,-,Non reconnue,904
...,...,...,...,...,...,...,...,...,...,...
243027,69009,ANSE,1982-08-16,1982-08-16,1982-09-21,1982-09-30,Inondations et/ou Coulées de Boue,Simple,Reconnue,48
243028,69052,CHAZAY D AZERGUES,1982-08-16,1982-08-16,1982-09-21,1982-09-30,Inondations et/ou Coulées de Boue,Simple,Reconnue,48
243029,69122,LUCENAY,1982-08-16,1982-08-16,1982-09-21,1982-09-30,Inondations et/ou Coulées de Boue,Simple,Reconnue,48
243030,69140,MORANCE,1982-08-16,1982-08-16,1982-09-21,1982-09-30,Inondations et/ou Coulées de Boue,Simple,Reconnue,48
243031,69163,QUINCIEUX,1982-08-16,1982-08-16,1982-09-21,1982-09-30,Inondations et/ou Coulées de Boue,Simple,Reconnue,48

In [6]:
df_ccr["date_debut_evenement"].describe()

count                        243032
mean     2003-05-18 15:01:56.962375
min             1982-08-15 00:00:00
25%             1990-06-26 00:00:00
50%             2003-07-01 00:00:00
75%             2017-01-01 00:00:00
max             2025-12-19 00:00:00
Name: date_debut_evenement, dtype: object

In [11]:
df_catnat_histo[df_catnat_histo["code_geo"] == '33166']

       code_geo  annee                  periode type_catnat  is_reconnue
0         33166   2003  2003-07-01 - 2003-09-30  Sécheresse         True
28614     33166   1991  1991-01-01 - 1998-06-30  Sécheresse         True
62885     33166   1990  1990-01-01 - 1990-12-31  Sécheresse         True
82586     33166   1983  1983-07-26 - 1983-07-27  Inondation         True
82587     33166   1983  1983-07-26 - 1983-07-27       Météo         True
82588     33166   1983  1983-07-26 - 1983-07-27       Météo         True
95574     33166   1982  1982-12-08 - 1982-12-31  Inondation         True
106881    33166   1982  1982-11-06 - 1982-11-10       Météo         True
106882    33166   1982  1982-11-06 - 1982-11-10  Inondation         True
140333    33166   2022  2022-01-01 - 2022-11-25  Sécheresse        False
147219    33166   2022  2022-06-20 - 2022-06-21  Inondation        False
169440    33166   2018  2018-01-01 - 2018-12-31  Sécheresse        False
175652    33166   2017  2017-04-01 - 2017-06-30  Sécheresse         True
204838    33166   2011  2011-04-01 - 2011-06-30  Sécheresse         True
204839    33166   2011  2011-07-01 - 2011-10-31  Sécheresse        False
220746    33166   2009  2009-01-24 - 2009-01-27  Inondation         True
220747    33166   2009  2009-01-24 - 2009-01-27       Marin         True