In [1]:
import pandas as pd
import duckdb

In [2]:
con = duckdb.connect('../../dev.duckdb')

In [3]:
df_pop = con.sql("SELECT * from population_par_com_annee").df()
df_pop.head(5)

  code_geo  annee_recensement  annee  population
0    45277               2013   2016         447
1    97230               2013   2016       13253
2    97219               2013   2016        1632
3    97208               2013   2016         813
4    97225               2013   2016        4285

In [4]:
df_pop.info()

<class 'pandas.DataFrame'>
RangeIndex: 384945 entries, 0 to 384944
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   code_geo           384945 non-null  str
 1   annee_recensement  384945 non-null  int32
 2   annee              384945 non-null  int32
 3   population         384742 non-null  Int64
dtypes: Int64(1), int32(2), str(1)
memory usage: 11.0 MB

In [9]:
df_pop.sort_values(by="code_geo", ascending=False)

       code_geo  annee_recensement  annee  population
89        97424               2013   2016        5386
35084     97424               2014   2017        5295
70079     97424               2015   2018        5350
105074    97424               2016   2019        5403
140069    97424               2017   2020        5456
...         ...                ...    ...         ...
228285    01001               2019   2022         779
263280    01001               2020   2023         806
298275    01001               2021   2024         832
333270    01001               2022   2025         859
368265    01001               2023   2026         860

[384945 rows x 4 columns]

In [5]:
df_pop[df_pop["population"].isnull()]

       code_geo  annee_recensement  annee  population
26980     76601               2013   2016        <NA>
61975     76601               2014   2017        <NA>
96970     76601               2015   2018        <NA>
131965    76601               2016   2019        <NA>
178493    21507               2018   2021        <NA>
...         ...                ...    ...         ...
383542    79060               2023   2026        <NA>
384370    49321               2023   2026        <NA>
384425    85037               2023   2026        <NA>
384543    18131               2023   2026        <NA>
384554    23023               2023   2026        <NA>

[203 rows x 4 columns]

In [10]:
df_commune = con.sql("SELECT * from insee_commune").df()
df_commune.tail(20)

,type_com,code_geo,reg,dep,ctcd,arr,tncc,ncc,nccenr,libelle,can,com_parent
37528,COM,97422,4,974,974D,9742,2,TAMPON,Tampon,Le Tampon,97499,NaN
37529,COM,97423,4,974,974D,9744,4,TROIS BASSINS,Trois-Bassins,Les Trois-Bassins,97414,NaN
37530,COM,97424,4,974,974D,9742,0,CILAOS,Cilaos,Cilaos,97416,NaN
37531,COM,97601,6,976,976D,NaN,1,ACOUA,Acoua,Acoua,97609,NaN
37532,COM,97602,6,976,976D,NaN,0,BANDRABOUA,Bandraboua,Bandraboua,97696,NaN
37533,COM,97603,6,976,976D,NaN,0,BANDRELE,Bandrele,Bandrele,97697,NaN
37534,COM,97604,6,976,976D,NaN,0,BOUENI,Bouéni,Bouéni,97602,NaN
37535,COM,97605,6,976,976D,NaN,0,CHICONI,Chiconi,Chiconi,97610,NaN
37536,COM,97606,6,976,976D,NaN,0,CHIRONGUI,Chirongui,Chirongui,97612,NaN
37537,COM,97607,6,976,976D,NaN,0,DEMBENI,Dembeni,Dembeni,97603,NaN
37538,COM,97608,6,976,976D,NaN,0,DZAOUDZI,Dzaoudzi,Dzaoudzi,97604,NaN
37539,COM,97609,6,976,976D,NaN,0,KANI KELI,Kani-Kéli,Kani-Kéli,97602,NaN
37540,COM,97610,6,976,976D,NaN,0,KOUNGOU,Koungou,Koungou,97698,NaN
37541,COM,97611,6,976,976D,NaN,0,MAMOUDZOU,Mamoudzou,Mamoudzou,97699,NaN
37542,COM,97612,6,976,976D,NaN,0,MTSAMBORO,Mtsamboro,Mtsamboro,97609,NaN
37543,COM,97613,6,976,976D,NaN,0,M TSANGAMOUJI,M'Tsangamouji,M'Tsangamouji,97613,NaN
37544,COM,97614,6,976,976D,NaN,1,OUANGANI,Ouangani,Ouangani,97610,NaN
37545,COM,97615,6,976,976D,NaN,0,PAMANDZI,Pamandzi,Pamandzi,97611,NaN
37546,COM,97616,6,976,976D,NaN,0,SADA,Sada,Sada,97612,NaN
37547,COM,97617,6,976,976D,NaN,0,TSINGONI,Tsingoni,Tsingoni,97613,NaN