In [1]:
import pandas as pd

In [2]:
df_tri_bats = pd.read_csv('../../pipeline_inputs/tri_all_bats_flat.csv')
df_rga_bats = pd.read_csv('../../pipeline_inputs/rga_houses_flat.csv')

/var/folders/fk/blb9jnzj5zg6sj7sp96423r80000gn/T/ipykernel_22472/1993834770.py:1: DtypeWarning: Columns (0: code_commune_insee) have mixed types. Specify dtype option on import or set low_memory=False.
  df_tri_bats = pd.read_csv('../../pipeline_inputs/tri_all_bats_flat.csv')
/var/folders/fk/blb9jnzj5zg6sj7sp96423r80000gn/T/ipykernel_22472/1993834770.py:2: DtypeWarning: Columns (0: code_commune_insee) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rga_bats = pd.read_csv('../../pipeline_inputs/rga_houses_flat.csv')

In [3]:
df_tri_bats.info()

<class 'pandas.DataFrame'>
RangeIndex: 34875 entries, 0 to 34874
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   code_commune_insee      34875 non-null  object
 1   agri_nul                34875 non-null  int64
 2   resid_nul               34875 non-null  int64
 3   autres_nul              34875 non-null  int64
 4   rervice_nul             34875 non-null  int64
 5   autres_faible           34875 non-null  int64
 6   agri_faible             34875 non-null  int64
 7   indus_nul               34875 non-null  int64
 8   autres_fort             34875 non-null  int64
 9   resid_moyen             34875 non-null  int64
 10  rervice_fort            34875 non-null  int64
 11  indus_moyen             34875 non-null  int64
 12  rervice_moyen           34875 non-null  int64
 13  autres_moyen            34875 non-null  int64
 14  rervice_faible          34875 non-null  int64
 15  resid_fort              34875 non-null  int64
 16  agri_fort               34875 non-null  int64
 17  resid_faible            34875 non-null  int64
 18  agri_moyen              34875 non-null  int64
 19  indus_faible            34875 non-null  int64
 20  indus_fort              34875 non-null  int64
 21  nb_bats_total           34875 non-null  int64
 22  nb_bats_exposition_tri  34875 non-null  int64
 23  pct_exposition_tri      34875 non-null  float64
dtypes: float64(1), int64(22), object(1)
memory usage: 6.4+ MB

In [4]:
df_rga_bats.info()

<class 'pandas.DataFrame'>
RangeIndex: 34782 entries, 0 to 34781
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   code_commune_insee         34782 non-null  object
 1   nb_maisons_total           34782 non-null  int64
 2   1945-1975_moyen            34782 non-null  int64
 3   pre1945_faible             34782 non-null  int64
 4   1945-1975_faible           34782 non-null  int64
 5   pre1945_nul                34782 non-null  int64
 6   post2020_faible            34782 non-null  int64
 7   1976-2020_nul              34782 non-null  int64
 8   post2020_moyen             34782 non-null  int64
 9   pre1945_fort               34782 non-null  int64
 10  1976-2020_faible           34782 non-null  int64
 11  1976-2020_moyen            34782 non-null  int64
 12  1976-2020_fort             34782 non-null  int64
 13  1945-1975_fort             34782 non-null  int64
 14  pre1945_moyen              34782 non-null  int64
 15  1945-1975_nul              34782 non-null  int64
 16  post2020_nul               34782 non-null  int64
 17  unk_fort                   34782 non-null  int64
 18  post2020_fort              34782 non-null  int64
 19  unk_faible                 34782 non-null  int64
 20  unk_moyen                  34782 non-null  int64
 21  unk_nul                    34782 non-null  int64
 22  nb_maisons_exposition_rga  34782 non-null  int64
 23  pct_exposition_rga         34782 non-null  float64
dtypes: float64(1), int64(22), object(1)
memory usage: 6.4+ MB

In [5]:
df_tri_bats.head(5)

,code_commune_insee,agri_nul,resid_nul,autres_nul,rervice_nul,autres_faible,agri_faible,indus_nul,autres_fort,resid_moyen,...,rervice_faible,resid_fort,agri_fort,resid_faible,agri_moyen,indus_faible,indus_fort,nb_bats_total,nb_bats_exposition_tri,pct_exposition_tri
0,01001,61,325,665,6,0,0,9,0,0,...,0,0,0,0,0,0,0,1066,0,0.0
1,01002,9,157,260,2,0,0,0,0,0,...,0,0,0,0,0,0,0,428,0,0.0
2,01004,11,3391,4341,378,0,0,288,0,0,...,0,0,0,0,0,0,0,8409,0,0.0
3,01005,74,625,891,23,0,0,14,0,0,...,0,0,0,0,0,0,0,1627,0,0.0
4,01006,10,58,94,1,0,0,0,0,0,...,0,0,0,0,0,0,0,163,0,0.0

In [7]:
df_tri_bats.columns

Index(['code_commune_insee', 'agri_nul', 'resid_nul', 'autres_nul',
       'rervice_nul', 'autres_faible', 'agri_faible', 'indus_nul',
       'autres_fort', 'resid_moyen', 'rervice_fort', 'indus_moyen',
       'rervice_moyen', 'autres_moyen', 'rervice_faible', 'resid_fort',
       'agri_fort', 'resid_faible', 'agri_moyen', 'indus_faible', 'indus_fort',
       'nb_bats_total', 'nb_bats_exposition_tri', 'pct_exposition_tri'],
      dtype='str')

In [6]:
df_rga_bats.head(5)

,code_commune_insee,nb_maisons_total,1945-1975_moyen,pre1945_faible,1945-1975_faible,pre1945_nul,post2020_faible,1976-2020_nul,post2020_moyen,pre1945_fort,...,pre1945_moyen,1945-1975_nul,post2020_nul,unk_fort,post2020_fort,unk_faible,unk_moyen,unk_nul,nb_maisons_exposition_rga,pct_exposition_rga
0,01001,358,0,123,21,0,19,0,1,0,...,7,0,1,0,0,0,0,0,357,0.997207
1,01002,168,12,5,1,0,0,3,1,0,...,118,0,1,0,0,0,0,0,164,0.976190
2,01004,3254,165,392,337,6,30,11,36,0,...,458,1,13,0,0,2,4,0,3223,0.990473
3,01005,616,0,121,82,2,70,2,0,0,...,0,0,11,0,0,0,0,0,601,0.975649
4,01006,62,0,44,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,62,1.000000