In [1]:
import pandas as pd
import duckdb

In [2]:
con = duckdb.connect('../../dev.duckdb')

In [3]:
df_tri_rga = con.sql("SELECT * from indicateurs_tri_rga_bats_par_com").df()
df_tri_rga.head(5)

  code_geo  indicateur_tri  indicateur_rga
0    01001             0.0        0.060475
1    01002             0.0        0.095238
2    01004             0.0        0.183190
3    01005             0.0        0.065584
4    01006             0.0        0.025000

In [4]:
df_tri_rga.info()

<class 'pandas.DataFrame'>
RangeIndex: 34875 entries, 0 to 34874
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   code_geo        34875 non-null  str
 1   indicateur_tri  34875 non-null  float64
 2   indicateur_rga  34737 non-null  float64
dtypes: float64(2), str(1)
memory usage: 987.8 KB

In [5]:
df_tri_rga[df_tri_rga["code_geo"].str.startswith('976')]

      code_geo  indicateur_tri  indicateur_rga
34858    97601        0.053409             NaN
34859    97602        0.042906             NaN
34860    97603        0.145953             NaN
34861    97604        0.073445             NaN
34862    97605        0.011047             NaN
34863    97606        0.042220             NaN
34864    97607        0.118687             NaN
34865    97608        0.057373             NaN
34866    97609        0.134692             NaN
34867    97610        0.112538             NaN
34868    97611        0.155165             NaN
34869    97612        0.042794             NaN
34870    97613        0.059692             NaN
34871    97614        0.000000             NaN
34872    97615        0.080519             NaN
34873    97616        0.020370             NaN
34874    97617        0.000154             NaN