## Exploration données batiments
[COLLECTE] Données date construction bâtiments
https://mattermost.services.dataforgood.fr/boards/team/4g8gayrar3r5d8ofobpk9kaxkr/bjjws538jrir4zxuh35r9kr35qo/vpki6pz3czj89fkjgth3kbq659r/cfti645hma3nbjn6woxwp7t9q9o

In [20]:
import pandas as pd
import numpy as np

In [2]:
bat = pd.read_csv('../csv/DS_RP_LOGEMENT_PRINC_2022_data.csv', delimiter=';')
bat.info()

/var/folders/wb/bg23zgwj389404sv03x64x2m0000gn/T/ipykernel_64020/794499090.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  bat = pd.read_csv('../csv/DS_RP_LOGEMENT_PRINC_2022_data.csv', delimiter=';')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8983400 entries, 0 to 8983399
Data columns (total 14 columns):
 #   Column       Dtype
---  ------       -----
 0   BUILD_END    object
 1   CARPARK      object
 2   CARS         object
 3   GEO          object
 4   GEO_OBJECT   object
 5   L_STAY       object
 6   NOR          object
 7   NRG_SRC      object
 8   OCS          object
 9   RP_MEASURE   object
 10  TDW          object
 11  TSH          object
 12  TIME_PERIOD  int64
 13  OBS_VALUE    float64
dtypes: float64(1), int64(1), object(12)
memory usage: 959.5+ MB

In [ ]:
bat_bdx = bat[
    (bat.GEO == '33063') &
    (bat.GEO_OBJECT == 'COM') &
    (bat.TIME_PERIOD == 2022)]

bat_bdx.head()

,BUILD_END,CARPARK,CARS,GEO,GEO_OBJECT,L_STAY,NOR,NRG_SRC,OCS,RP_MEASURE,TDW,TSH,TIME_PERIOD,OBS_VALUE
3875229,_T,_T,_T,33063,COM,_T,_T,_T,DW_VAC,DWELLINGS,3T6,_T,2022,25.91203
3986726,_T,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,114015.48661
3988000,_T,_T,_T,33063,COM,_T,_T,_T,DW_VAC,DWELLINGS,2,_T,2022,10139.17129
3989482,_T,_T,_T,33063,COM,_T,_T,_T,DW_SEC_DW_OCC,DWELLINGS,2,_T,2022,8676.67451
3992361,_T,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,31674.76996

In [ ]:
bat_bdx[~(bat_bdx.BUILD_END == '_T')]

,BUILD_END,CARPARK,CARS,GEO,GEO_OBJECT,L_STAY,NOR,NRG_SRC,OCS,RP_MEASURE,TDW,TSH,TIME_PERIOD,OBS_VALUE
5500120,Y1946T1970,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,5973.98528
5500432,Y2006TAAAA,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,18198.23176
5501268,Y1971T1990,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,25380.62653
5501547,Y2006TAAAA,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,168.81691
5502903,Y1946T1970,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,19035.98655
5505961,Y1991T2005,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,17420.45783
5524174,Y1919T1945,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,8920.01887
5525816,Y1971T1990,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,153.39615
5526492,Y1919T1945,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,7638.10558
5526995,Y1991T2005,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,249.08478
5526996,Y1946T1970,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,83.37428
5559653,Y1971T1990,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,3166.75681
5560072,Y2006TAAAA,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,1739.63030
5560870,Y_LT1919,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,22782.19507
5562060,Y_LT1919,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,80.06968
5562126,Y_LT1919,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,10370.73829
5562285,Y1919T1945,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,72.96064
5562994,Y1991T2005,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,2582.09655
6338216,Y1919T1945,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,16631.08509
6343856,Y_LT1919,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,33233.00304
6345770,Y1991T2005,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,20251.63916
6346197,Y1946T1970,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,25093.34612
6349704,Y1971T1990,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,28700.77949
6352077,Y2006TAAAA,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,20106.67897

In [ ]:
bat.head()

,BUILD_END,CARPARK,CARS,GEO,GEO_OBJECT,L_STAY,NOR,NRG_SRC,OCS,RP_MEASURE,TDW,TSH,TIME_PERIOD,OBS_VALUE
0,_T,_T,_T,64265,COM,_T,_T,OTH,DW_MAIN,DWELLINGS,_T,_T,2016,20.25000
1,_T,_T,_T,60343,COM,_T,_T,ELC,DW_MAIN,DWELLINGS,_T,_T,2016,96.38595
2,_T,_T,_T,625,ARR,_T,R1,_T,DW_MAIN,DWELLINGS,_T,_T,2011,988.76189
3,_T,_T,_T,133,ARR,_T,R1,_T,DW_MAIN,DWELLINGS,_T,_T,2011,34650.54961
4,_T,_T,_T,63398,COM,_T,_T,ELC,DW_MAIN,DWELLINGS,_T,_T,2016,1.97938

In [3]:
bat_com = bat[
    ~(bat.BUILD_END == '_T') &      # On ignore les totaux qui donnent des découpages selon d'autres axes d'analyses
    ~(bat.TDW == '_T') &            # Type de logement (On ignore le total pour ne pas compter deux fois) 
    (bat.GEO_OBJECT == 'COM') &     # On ne garde que les communes (attention pour les PLM)
    (bat.TIME_PERIOD == 2022)     # Pour l'instant on ne garde que la denière année (2022)
] 
bat_com.info()

<class 'pandas.core.frame.DataFrame'>
Index: 358919 entries, 3853780 to 6549873
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   BUILD_END    358919 non-null  object
 1   CARPARK      358919 non-null  object
 2   CARS         358919 non-null  object
 3   GEO          358919 non-null  object
 4   GEO_OBJECT   358919 non-null  object
 5   L_STAY       358919 non-null  object
 6   NOR          358919 non-null  object
 7   NRG_SRC      358919 non-null  object
 8   OCS          358919 non-null  object
 9   RP_MEASURE   358919 non-null  object
 10  TDW          358919 non-null  object
 11  TSH          358919 non-null  object
 12  TIME_PERIOD  358919 non-null  int64
 13  OBS_VALUE    358919 non-null  float64
dtypes: float64(1), int64(1), object(12)
memory usage: 41.1+ MB

In [4]:
del bat #save memory

In [28]:
bat_com_agg = bat_com[['GEO', 'BUILD_END','OBS_VALUE']].groupby(['GEO', 'BUILD_END']).sum('OBS_VALUE').reset_index()
bat_com_agg = bat_com_agg.pivot_table(index='GEO', columns=['BUILD_END'], values='OBS_VALUE').reset_index()
year_col = [col for col in bat_com_agg.columns.values if col.startswith('Y')]
bat_com_agg['Total'] = bat_com_agg[year_col].sum(axis=1)
bat_com_agg.head()

BUILD_END,GEO,Y1919T1945,Y1946T1970,Y1971T1990,Y1991T2005,Y2006TAAAA,Y_LT1919,Total
0,01001,22.00000,15.00000,100.00000,88.00000,37.00000,77.00000,339.00000
1,01002,6.00000,13.00000,9.00000,10.00000,20.00000,61.00000,119.00000
2,01004,382.08249,1353.83441,1759.04881,1412.05155,1760.49638,340.19455,7007.70819
3,01005,36.15079,83.04341,217.29169,149.04367,212.80010,111.83214,810.16180
4,01006,5.00000,5.00000,10.00000,9.00000,12.00000,16.00000,57.00000

In [16]:
bat_com_agg.head()

BUILD_END,GEO,Y1919T1945,Y1946T1970,Y1971T1990,Y1991T2005,Y2006TAAAA,Y_LT1919,Total
0,01001,22.00000,15.00000,100.00000,88.00000,37.00000,77.00000,"[Y1919T1945, Y1946T1970, Y1971T1990, Y1991T200..."
1,01002,6.00000,13.00000,9.00000,10.00000,20.00000,61.00000,"[Y1919T1945, Y1946T1970, Y1971T1990, Y1991T200..."
2,01004,382.08249,1353.83441,1759.04881,1412.05155,1760.49638,340.19455,"[Y1919T1945, Y1946T1970, Y1971T1990, Y1991T200..."
3,01005,36.15079,83.04341,217.29169,149.04367,212.80010,111.83214,"[Y1919T1945, Y1946T1970, Y1971T1990, Y1991T200..."
4,01006,5.00000,5.00000,10.00000,9.00000,12.00000,16.00000,"[Y1919T1945, Y1946T1970, Y1971T1990, Y1991T200..."

In [ ]:
bat_com_agg[bat_com_agg.GEO == '33063']

BUILD_END,GEO,Y1919T1945,Y1946T1970,Y1971T1990,Y1991T2005,Y2006TAAAA,Y_LT1919,_T
18994,33063,33262.17018,50186.69223,57401.55898,40503.27832,40213.35794,66466.00608,6.409187e+06